name: Run Tests

on:
  push:
    branches:
      - main
      - master
jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: 3.11
      - name: Create virtual environment
        run: python -m venv .venv
      - name: Activate virtual environment
        run: source .venv/bin/activate
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Start tests
        run: pytest test_my_app.py

      - name: Upload test results
        uses: actions/upload-artifact@v2
        with:
          name: Test Results
          path: test_results.xml
